name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11

      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org"

      - run: npm install -g junit-merge
      - run: npm install -g junit-viewer

      - name: Configure ntp time
        run: |
          sudo apt-get install ntp -y
          sudo ntptime -T 37

      - name: Build
        run: |
          sbt test:compile multi-jvm:compile
          sbt makeSite

      - name: Unit and Component Tests
        run: |
          sbt -DenableCoverage=true -DgenerateStoryReport=true csw-time/test:test
          sbt -DenableCoverage=true -DgenerateStoryReport=true -DdisableTimeTests test:test

      - name: Coverage Report
        run: |
          sbt -DenableCoverage=true coverageReport
          sbt coverageAggregate

      - uses: actions/upload-artifact@v1
        with:
          name: Coverage Report
          path: target/scala-2.13/scoverage-report

      - name: Delete js targets
        continue-on-error: true
        run: find . -type d -regex ".*js/target.*" | xargs rm -rf

      - name: Multi-Jvm Tests
        run: sbt -DgenerateStoryReport=true integration/multi-jvm:test

      - name: Generate RTM
        run: |
          ./scripts/coursier launch --channel https://raw.githubusercontent.com/tmtsoftware/apps/master/apps.json rtm:d1c8c7e -- target/RTM/testStoryMapping.txt tools/RTM/cswStoryToRequirementMap.csv target/RTM/testRequirementsMapping.txt

      - name: Upload RTM
        uses: actions/upload-artifact@v1
        with:
          name: RTM
          path: target/RTM

      - name: Github Release
        run: sbt -Dprod.publish=true githubRelease
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Docs Publish
        run: |
          echo 'echo $RELEASE_TOKEN' > /tmp/.git-askpass
          chmod +x /tmp/.git-askpass
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Action"
          sbt -Dprod.publish=true clean ghpagesPushSite
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_ASKPASS: /tmp/.git-askpass

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-release
